# Generated by Django 3.1.7 on 2021-06-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopsinfo',
            old_name='shopename',
            new_name='shopname',
        ),
    ]
