# Generated by Django 3.1.5 on 2021-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart',
            old_name='casing',
            new_name='item_link',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='harddisk',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='processor_cooler',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='processors',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='ssd',
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
