# Generated by Django 3.1.5 on 2021-02-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0002_auto_20210206_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
