# Generated by Django 3.1.5 on 2021-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0004_user_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsinfo',
            name='casing',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='gpu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='harddisk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='motherboard',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='processor_cooler',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='processors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='ram',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='ssd',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
