# Generated by Django 3.1.5 on 2021-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0005_auto_20210206_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='shop_id',
        ),
    ]
