# Generated by Django 3.1.5 on 2021-02-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0006_auto_20210206_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='shop_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_builder.shopsinfo'),
        ),
    ]
