# Generated by Django 3.1.5 on 2021-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0007_auto_20210206_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
