# Generated by Django 3.1.5 on 2021-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0008_auto_20210206_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='casing',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='harddisk',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='processor_cooler',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='processors',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='shopsinfo',
            name='ssd',
        ),
        migrations.AddField(
            model_name='shopsinfo',
            name='shopimgaddress',
            field=models.CharField(default='NULL', max_length=500),
        ),
    ]
