# Generated by Django 3.1.5 on 2021-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0009_auto_20210222_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsinfo',
            name='addedtime',
            field=models.DateTimeField(default=1613976772.2710445),
        ),
    ]
