# Generated by Django 3.1.5 on 2021-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0012_auto_20210222_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsinfo',
            name='addedtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
