# Generated by Django 3.1.5 on 2021-02-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0014_auto_20210222_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsinfo',
            name='addedtime',
        ),
    ]
