# Generated by Django 3.1.5 on 2021-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0015_remove_shopsinfo_addedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsinfo',
            name='time',
            field=models.DateTimeField(default= '2021-02-06 06:00:00+06'),
        ),
    ]
