# Generated by Django 3.1.5 on 2021-02-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0017_remove_shopsinfo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart',
            name='time',
        ),
    ]
