# Generated by Django 3.1.5 on 2021-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0020_shopsinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsinfo',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
