# Generated by Django 3.1.5 on 2021-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0021_auto_20210222_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsinfo',
            name='shopaddress',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='shopename',
            field=models.CharField(default=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='shopimgaddress',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='shopsinfo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_cart',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
