# Generated by Django 3.1.5 on 2021-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0022_auto_20210222_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsinfo',
            name='time',
        ),
        migrations.RemoveField(
            model_name='user_cart',
            name='time',
        ),
    ]
